FROM python:3.10 AS base

WORKDIR /app
RUN pip install uv
RUN uv venv
COPY requirements-cpu.txt requirements-cpu.txt
RUN uv pip install -r requirements-cpu.txt --index-strategy unsafe-best-match

FROM python:3.10-slim-bookworm
WORKDIR /app
COPY --from=base /app/.venv .venv
COPY init.py init.py
RUN .venv/bin/python init.py

COPY main.py main.py
COPY common.py common.py

ENTRYPOINT [".venv/bin/python", "main.py"]